-- INITIALISATION TABLE SUBSCRIBER
INSERT INTO SUBSCRIBER (SUBSCRIBER_ID, NOM, PRENOM, ADRESSE) values (1, 'Ait Lhadj', 'Amine', '41 rue Casteres');

INSERT INTO SUBSCRIBER (SUBSCRIBER_ID, NOM, PRENOM, ADRESSE) values (2, 'Fisher', 'Jack', '144 Oxford City');

-- INITIIALISATION TABLE SUBSCRIPTION
INSERT INTO SUBSCRIPTION (SUBSCRIPTION_ID, ADRESSE) values (1, '41 rue casteres');

INSERT INTO SUBSCRIPTION (SUBSCRIPTION_ID, ADRESSE) values (2, '144 Oxford City');

-- INITIALISATION TABLE MOVEMET
--INSERT INTO MOVEMENT (MOVEMENT_ID, MODIFICATION_TYPE, MODIFICATION_DATE, OLD_VALUE, NEW_VALUE) values (1, 'Adresse', null, null, null);

-- TABLE DE JOINTURE
INSERT INTO SUBSCRIBER_SUBCRIPTION (SUBSCRIBER_ID, SUBSCRIPTION_ID) values (1,1);
INSERT INTO SUBSCRIBER_SUBCRIPTION (SUBSCRIBER_ID, SUBSCRIPTION_ID) values (2,2);

COMMIT;